language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libsfml-dev; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sfml; fi
script:
- make
- make test
- ./tests_delaunay --durations yes
after_success:
- echo "Success"
branches:
  only:
  - master
  - "/^v\\d+\\./"
